[tool.poetry]
name = "crm-ddd-poc"
version = "0.1.0"
description = ""
authors = ["Dominik <*******@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
email-validator = "^2.2.0"
phonenumbers = "^8.13.43"
attrs = "^24.2.0"
fastapi = {extras = ["standard"], version = "^0.112.2"}
pydantic = "^2.8.2"
faker = "^28.4.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
