"""initial

Revision ID: fac9bf3b26f9
Revises:
Create Date: 2024-10-25 21:42:42.942382

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fac9bf3b26f9"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "country",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("code", sa.String(length=2), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_country_id"), "country", ["id"], unique=False)
    op.create_table(
        "currency",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("iso_code", sa.String(length=3), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("iso_code"),
    )
    op.create_index(op.f("ix_currency_id"), "currency", ["id"], unique=False)
    op.create_table(
        "customer",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("relation_manager_id", sa.String(), nullable=False),
        sa.Column("status_name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_customer_id"), "customer", ["id"], unique=False)
    op.create_index(op.f("ix_customer_relation_manager_id"), "customer", ["relation_manager_id"], unique=False)
    op.create_table(
        "language",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("code", sa.String(length=2), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_language_id"), "language", ["id"], unique=False)
    op.create_table(
        "lead",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("customer_id", sa.String(), nullable=False),
        sa.Column("created_by_id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("source_name", sa.String(), nullable=False),
        sa.Column("contact_data_first_name", sa.String(), nullable=False),
        sa.Column("contact_data_last_name", sa.String(), nullable=False),
        sa.Column("contact_data_phone", sa.String(), nullable=True),
        sa.Column("contact_data_email", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_lead_created_by_id"), "lead", ["created_by_id"], unique=False)
    op.create_index(op.f("ix_lead_customer_id"), "lead", ["customer_id"], unique=False)
    op.create_index(op.f("ix_lead_id"), "lead", ["id"], unique=False)
    op.create_table(
        "opportunity",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_by_id", sa.String(), nullable=False),
        sa.Column("customer_id", sa.String(), nullable=False),
        sa.Column("owner_id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("source_name", sa.String(), nullable=False),
        sa.Column("stage_name", sa.String(), nullable=False),
        sa.Column("priority_level", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_opportunity_id"), "opportunity", ["id"], unique=False)
    op.create_table(
        "product",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_product_id"), "product", ["id"], unique=False)
    op.create_table(
        "sales_representative",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sales_representative_id"), "sales_representative", ["id"], unique=False)
    op.create_table(
        "address",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("country_id", sa.String(), nullable=False),
        sa.Column("street", sa.String(), nullable=False),
        sa.Column("street_no", sa.String(), nullable=False),
        sa.Column("postal_code", sa.String(), nullable=False),
        sa.Column("city", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["country_id"],
            ["country.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_address_country_id"), "address", ["country_id"], unique=False)
    op.create_index(op.f("ix_address_id"), "address", ["id"], unique=False)
    op.create_table(
        "contact_person",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("language_id", sa.String(), nullable=False),
        sa.Column("customer_id", sa.String(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.Column("job_title", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customer.id"],
        ),
        sa.ForeignKeyConstraint(
            ["language_id"],
            ["language.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_contact_person_customer_id"), "contact_person", ["customer_id"], unique=False)
    op.create_index(op.f("ix_contact_person_id"), "contact_person", ["id"], unique=False)
    op.create_index(op.f("ix_contact_person_language_id"), "contact_person", ["language_id"], unique=False)
    op.create_table(
        "lead_assignment",
        sa.Column("lead_id", sa.String(), nullable=False),
        sa.Column("previous_owner_id", sa.String(), nullable=True),
        sa.Column("new_owner_id", sa.String(), nullable=False),
        sa.Column("assigned_by_id", sa.String(), nullable=False),
        sa.Column("assigned_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["lead_id"],
            ["lead.id"],
        ),
        sa.PrimaryKeyConstraint("lead_id", "new_owner_id", "assigned_by_id"),
    )
    op.create_index(op.f("ix_lead_assignment_lead_id"), "lead_assignment", ["lead_id"], unique=False)
    op.create_table(
        "lead_note",
        sa.Column("lead_id", sa.String(), nullable=False),
        sa.Column("created_by_id", sa.String(), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["lead_id"],
            ["lead.id"],
        ),
        sa.PrimaryKeyConstraint("lead_id", "created_by_id", "content"),
    )
    op.create_index(op.f("ix_lead_note_lead_id"), "lead_note", ["lead_id"], unique=False)
    op.create_table(
        "offer_item",
        sa.Column("opportunity_id", sa.String(), nullable=False),
        sa.Column("product_id", sa.String(), nullable=False),
        sa.Column("currency_id", sa.String(), nullable=False),
        sa.Column("amount", sa.Numeric(), nullable=False),
        sa.ForeignKeyConstraint(
            ["currency_id"],
            ["currency.id"],
        ),
        sa.ForeignKeyConstraint(
            ["opportunity_id"],
            ["opportunity.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.PrimaryKeyConstraint("opportunity_id", "product_id", "currency_id", "amount"),
    )
    op.create_index(op.f("ix_offer_item_currency_id"), "offer_item", ["currency_id"], unique=False)
    op.create_index(op.f("ix_offer_item_opportunity_id"), "offer_item", ["opportunity_id"], unique=False)
    op.create_index(op.f("ix_offer_item_product_id"), "offer_item", ["product_id"], unique=False)
    op.create_table(
        "opportunity_note",
        sa.Column("opportunity_id", sa.String(), nullable=False),
        sa.Column("created_by_id", sa.String(), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["opportunity_id"],
            ["opportunity.id"],
        ),
        sa.PrimaryKeyConstraint("opportunity_id", "created_by_id", "content"),
    )
    op.create_index(op.f("ix_opportunity_note_opportunity_id"), "opportunity_note", ["opportunity_id"], unique=False)
    op.create_table(
        "company_data",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("address_id", sa.String(), nullable=False),
        sa.Column("customer_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("industry_name", sa.String(), nullable=False),
        sa.Column("size", sa.String(), nullable=False),
        sa.Column("legal_form", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["address_id"],
            ["address.id"],
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customer.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_company_data_address_id"), "company_data", ["address_id"], unique=False)
    op.create_index(op.f("ix_company_data_customer_id"), "company_data", ["customer_id"], unique=False)
    op.create_index(op.f("ix_company_data_id"), "company_data", ["id"], unique=False)
    op.create_table(
        "contact_method",
        sa.Column("contact_person_id", sa.String(), nullable=False),
        sa.Column("value", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("is_preferred", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["contact_person_id"],
            ["contact_person.id"],
        ),
        sa.PrimaryKeyConstraint("contact_person_id", "value"),
        sa.UniqueConstraint("value"),
    )
    op.create_index(op.f("ix_contact_method_contact_person_id"), "contact_method", ["contact_person_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_contact_method_contact_person_id"), table_name="contact_method")
    op.drop_table("contact_method")
    op.drop_index(op.f("ix_company_data_id"), table_name="company_data")
    op.drop_index(op.f("ix_company_data_customer_id"), table_name="company_data")
    op.drop_index(op.f("ix_company_data_address_id"), table_name="company_data")
    op.drop_table("company_data")
    op.drop_index(op.f("ix_opportunity_note_opportunity_id"), table_name="opportunity_note")
    op.drop_table("opportunity_note")
    op.drop_index(op.f("ix_offer_item_product_id"), table_name="offer_item")
    op.drop_index(op.f("ix_offer_item_opportunity_id"), table_name="offer_item")
    op.drop_index(op.f("ix_offer_item_currency_id"), table_name="offer_item")
    op.drop_table("offer_item")
    op.drop_index(op.f("ix_lead_note_lead_id"), table_name="lead_note")
    op.drop_table("lead_note")
    op.drop_index(op.f("ix_lead_assignment_lead_id"), table_name="lead_assignment")
    op.drop_table("lead_assignment")
    op.drop_index(op.f("ix_contact_person_language_id"), table_name="contact_person")
    op.drop_index(op.f("ix_contact_person_id"), table_name="contact_person")
    op.drop_index(op.f("ix_contact_person_customer_id"), table_name="contact_person")
    op.drop_table("contact_person")
    op.drop_index(op.f("ix_address_id"), table_name="address")
    op.drop_index(op.f("ix_address_country_id"), table_name="address")
    op.drop_table("address")
    op.drop_index(op.f("ix_sales_representative_id"), table_name="sales_representative")
    op.drop_table("sales_representative")
    op.drop_index(op.f("ix_product_id"), table_name="product")
    op.drop_table("product")
    op.drop_index(op.f("ix_opportunity_id"), table_name="opportunity")
    op.drop_table("opportunity")
    op.drop_index(op.f("ix_lead_id"), table_name="lead")
    op.drop_index(op.f("ix_lead_customer_id"), table_name="lead")
    op.drop_index(op.f("ix_lead_created_by_id"), table_name="lead")
    op.drop_table("lead")
    op.drop_index(op.f("ix_language_id"), table_name="language")
    op.drop_table("language")
    op.drop_index(op.f("ix_customer_relation_manager_id"), table_name="customer")
    op.drop_index(op.f("ix_customer_id"), table_name="customer")
    op.drop_table("customer")
    op.drop_index(op.f("ix_currency_id"), table_name="currency")
    op.drop_table("currency")
    op.drop_index(op.f("ix_country_id"), table_name="country")
    op.drop_table("country")
    # ### end Alembic commands ###
